[package]
name = "build-page"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.43", features = ["derive"] }
comrak = "0.40"
regex = "1.11.1"
walkdir = "2.5.0"
